// src/views/News.vue

<template>
  <div class="container py-5">
    <h1 class="mb-4">Latest News & Updates</h1>

    <!-- Search and filters -->
    <div class="row mb-4">
      <div class="col-md-6 mb-3 mb-md-0">
        <div class="input-group">
          <input 
            type="text" 
            class="form-control" 
            placeholder="Search news..." 
            v-model="searchQuery"
            @input="applyFilters"
          >
          <button class="btn btn-primary" type="button">
            <i class="bi bi-search"></i>
          </button>
        </div>
      </div>

      <div class="col-md-3 mb-3 mb-md-0">
        <select class="form-select" v-model="selectedCategory" @change="applyFilters">
          <option value="">All Categories</option>
          <option v-for="category in categories" :key="category" :value="category">
            {{ category }}
          </option>
        </select>
      </div>

      <div class="col-md-3">
        <input 
          type="date" 
          class="form-control" 
          v-model="dateFilter"
          @change="applyFilters"
        >
      </div>
    </div>

    <div v-if="filteredNews.length === 0" class="text-center py-5">
      <p class="mb-3">No news articles found matching your criteria.</p>
      <button class="btn btn-outline-primary" @click="resetFilters">Reset Filters</button>
    </div>

    <div v-else class="row">
      <div v-for="item in paginatedNews" :key="item.id" class="col-md-6 col-lg-4 mb-4">
        <div class="card h-100">
          <img :src="item.image" class="card-img-top" alt="News Image" style="height: 200px; object-fit: cover;">
          <div class="card-body">
            <div class="d-flex justify-content-between mb-2">
              <small class="text-muted">{{ formatDate(item.date) }}</small>
              <span class="badge bg-secondary">{{ item.category }}</span>
            </div>
            <h5 class="card-title">{{ item.title }}</h5>
            <p class="card-text">{{ truncateText(item.content) }}</p>
          </div>
          <div class="card-footer bg-white d-flex justify-content-between align-items-center">
            <button class="btn btn-sm btn-outline-danger" @click="toggleLike(item)">
              <i class="bi" :class="[item.isLiked ? 'bi-heart-fill' : 'bi-heart']"></i>
              {{ item.likes }}
            </button>
            <a href="#" class="text-primary" @click.prevent="readMore(item)">Read more</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Pagination -->
    <nav v-if="totalPages > 1" class="mt-4">
      <ul class="pagination justify-content-center">
        <li class="page-item" :class="{ disabled: currentPage === 1 }">
          <a class="page-link" href="#" @click.prevent="changePage(currentPage - 1)">Previous</a>
        </li>
        <li v-for="page in totalPages" :key="page" class="page-item" :class="{ active: page === currentPage }">
          <a class="page-link" href="#" @click.prevent="changePage(page)">{{ page }}</a>
        </li>
        <li class="page-item" :class="{ disabled: currentPage === totalPages }">
          <a class="page-link" href="#" @click.prevent="changePage(currentPage + 1)">Next</a>
        </li>
      </ul>
    </nav>

    <!-- Article Modal -->
    <div class="modal fade" id="newsModal" tabindex="-1" aria-labelledby="newsModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg">
        <div class="modal-content" v-if="selectedArticle">
          <div class="modal-header">
            <h5 class="modal-title" id="newsModalLabel">{{ selectedArticle.title }}</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <img :src="selectedArticle.image" class="img-fluid rounded mb-3" alt="Article image">
            <div class="d-flex justify-content-between mb-3">
              <span class="text-muted">{{ formatDate(selectedArticle.date) }}</span>
              <span class="badge bg-secondary">{{ selectedArticle.category }}</span>
            </div>
            <p>{{ selectedArticle.content }}</p>
          </div>
          <div class="modal-footer">
            <button class="btn btn-outline-danger me-auto" @click="toggleLike(selectedArticle)">
              <i class="bi" :class="[selectedArticle.isLiked ? 'bi-heart-fill' : 'bi-heart']"></i>
              {{ selectedArticle.likes }}
            </button>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import newsData from '../data/news.js';

// State
const news = ref([]);
const filteredNews = ref([]);
const searchQuery = ref('');
const selectedCategory = ref('');
const dateFilter = ref('');
const currentPage = ref(1);
const itemsPerPage = 6;
const selectedArticle = ref(null);
let modalInstance = null;

// Computed properties
const categories = computed(() => {
  return [...new Set(news.value.map(item => item.category))];
});

const totalPages = computed(() => {
  return Math.ceil(filteredNews.value.length / itemsPerPage);
});

const paginatedNews = computed(() => {
  const startIndex = (currentPage.value - 1) * itemsPerPage;
  const endIndex = startIndex + itemsPerPage;
  return filteredNews.value.slice(startIndex, endIndex);
});

// Methods
const applyFilters = () => {
  let result = [...news.value];
  
  // Filter by search query
  if (searchQuery.value) {
    const query = searchQuery.value.toLowerCase();
    result = result.filter(item => 
      item.title.toLowerCase().includes(query) || 
      item.content.toLowerCase().includes(query)
    );
  }
  
  // Filter by category
  if (selectedCategory.value) {
    result = result.filter(item => item.category === selectedCategory.value);
  }
  
  // Filter by date
  if (dateFilter.value) {
    const filterDate = new Date(dateFilter.value).setHours(0, 0, 0, 0);
    result = result.filter(item => {
      const itemDate = new Date(item.date).setHours(0, 0, 0, 0);
      return itemDate === filterDate;
    });
  }
  
  filteredNews.value = result;
  currentPage.value = 1; // Reset to first page when filters change
};

const resetFilters = () => {
  searchQuery.value = '';
  selectedCategory.value = '';
  dateFilter.value = '';
  applyFilters();
};

const changePage = (page) => {
  if (page >= 1 && page <= totalPages.value) {
    currentPage.value = page;
    window.scrollTo(0, 0);
  }
};

const truncateText = (text, length = 100) => {
  return text.length > length ? text.substring(0, length) + '...' : text;
};

const formatDate = (dateString) => {
  return new Date(dateString).toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
};

const toggleLike = (item) => {
  item.isLiked = !item.isLiked;
  if (item.isLiked) {
    item.likes++;
  } else {
    item.likes--;
  }
};

const readMore = (item) => {
  selectedArticle.value = item;
  
  // Use Bootstrap's modal API to show the modal
  if (modalInstance) {
    modalInstance.show();
  } else {
    // Initialize modal if it doesn't exist yet
    const modalElement = document.getElementById('newsModal');
    if (modalElement) {
      // Assuming Bootstrap is loaded
      modalInstance = new bootstrap.Modal(modalElement);
      modalInstance.show();
    }
  }
};

// Lifecycle hooks
onMounted(() => {
  // Add isLiked property to each news item
  news.value = newsData.map(item => ({
    ...item,
    isLiked: false
  }));
  
  filteredNews.value = news.value;
});
</script>

// src/pages/News.tsx

import { useState, useEffect } from "react";
import NewsCard from "@/components/NewsCard";
import newsData from "@/data/news.json";
import { Search } from "lucide-react";

const News = () => {
  const [news, setNews] = useState(newsData);
  const [filteredNews, setFilteredNews] = useState(newsData);
  const [currentPage, setCurrentPage] = useState(1);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedCategory, setSelectedCategory] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  
  const newsPerPage = 6;
  
  // Get unique categories
  const categories = [...new Set(newsData.map(item => item.category))];
  
  // Filter news when filters change
  useEffect(() => {
    let result = newsData;
    
    // Filter by search query (checks title and content)
    if (searchQuery) {
      result = result.filter(item => 
        item.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
        item.content.toLowerCase().includes(searchQuery.toLowerCase())
      );
    }
    
    // Filter by category
    if (selectedCategory) {
      result = result.filter(item => item.category === selectedCategory);
    }
    
    // Filter by date range
    if (startDate) {
      const start = new Date(startDate);
      result = result.filter(item => new Date(item.date) >= start);
    }
    
    if (endDate) {
      const end = new Date(endDate);
      end.setHours(23, 59, 59, 999); // Set to end of day
      result = result.filter(item => new Date(item.date) <= end);
    }
    
    setFilteredNews(result);
    setCurrentPage(1); // Reset to first page when filters change
  }, [searchQuery, selectedCategory, startDate, endDate]);
  
  // Calculate pagination
  const indexOfLastNews = currentPage * newsPerPage;
  const indexOfFirstNews = indexOfLastNews - newsPerPage;
  const currentNews = filteredNews.slice(indexOfFirstNews, indexOfLastNews);
  
  const totalPages = Math.ceil(filteredNews.length / newsPerPage);
  
  const paginate = (pageNumber: number) => {
    if (pageNumber > 0 && pageNumber <= totalPages) {
      setCurrentPage(pageNumber);
      // Scroll to top of news grid
      document.getElementById("news-grid")?.scrollIntoView({ behavior: "smooth" });
    }
  };
  
  // Handle search form submission
  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    // Search is already handled by the useEffect, this just prevents form submission
  };
  
  // Reset all filters
  const resetFilters = () => {
    setSearchQuery("");
    setSelectedCategory("");
    setStartDate("");
    setEndDate("");
    setFilteredNews(newsData);
  };
  
  // Handle like toggle
  const handleLikeToggle = (id: string, liked: boolean) => {
    // In a real app, this would update the backend
    console.log(`News ${id} ${liked ? 'liked' : 'unliked'}`);
  };
  
  return (
    <div className="min-h-screen pt-20 pb-16">
      <div className="container mx-auto px-4">
        {/* Page header */}
        <div className="mb-10 text-center">
          <h1 className="text-4xl font-bold mb-4">Latest News</h1>
          <p className="text-gray-600 max-w-2xl mx-auto">
            Stay updated with the latest news, announcements, and articles from ShopVue.
          </p>
        </div>
        
        <div className="flex flex-col lg:flex-row gap-8">
          {/* Filter sidebar */}
          <div className="lg:w-1/4 space-y-6">
            <div className="bg-white p-5 rounded-lg shadow-md">
              <h2 className="text-lg font-semibold mb-4">Filters</h2>
              
              {/* Search */}
              <div className="mb-6">
                <form onSubmit={handleSearch} className="relative">
                  <input
                    type="text"
                    placeholder="Search news..."
                    className="w-full pl-10 pr-4 py-2 rounded-md border border-gray-300 focus:outline-none focus:ring-2 focus:ring-primary transition"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                  />
                  <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-4 h-4" />
                </form>
              </div>
              
              {/* Categories */}
              <div className="mb-6">
                <h3 className="text-md font-medium mb-2">Categories</h3>
                <div className="space-y-2">
                  <div className="flex items-center">
                    <input
                      type="radio"
                      id="all-categories"
                      name="category"
                      checked={selectedCategory === ""}
                      onChange={() => setSelectedCategory("")}
                      className="mr-2"
                    />
                    <label htmlFor="all-categories">All Categories</label>
                  </div>
                  
                  {categories.map(category => (
                    <div key={category} className="flex items-center">
                      <input
                        type="radio"
                        id={category}
                        name="category"
                        checked={selectedCategory === category}
                        onChange={() => setSelectedCategory(category)}
                        className="mr-2"
                      />
                      <label htmlFor={category}>{category}</label>
                    </div>
                  ))}
                </div>
              </div>
              
              {/* Date Range */}
              <div className="mb-6">
                <h3 className="text-md font-medium mb-2">Date Range</h3>
                <div className="space-y-3">
                  <div>
                    <label htmlFor="start-date" className="block text-sm text-gray-600 mb-1">
                      From
                    </label>
                    <input
                      type="date"
                      id="start-date"
                      value={startDate}
                      onChange={(e) => setStartDate(e.target.value)}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
                    />
                  </div>
                  <div>
                    <label htmlFor="end-date" className="block text-sm text-gray-600 mb-1">
                      To
                    </label>
                    <input
                      type="date"
                      id="end-date"
                      value={endDate}
                      min={startDate}
                      onChange={(e) => setEndDate(e.target.value)}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-primary"
                    />
                  </div>
                </div>
              </div>
              
              {/* Reset Filters */}
              <button
                onClick={resetFilters}
                className="w-full bg-gray-200 hover:bg-gray-300 text-gray-800 py-2 px-4 rounded-md transition-colors"
              >
                Reset Filters
              </button>
            </div>
          </div>
          
          {/* News grid */}
          <div className="lg:w-3/4">
            {/* Results count */}
            <div className="mb-6">
              <p className="text-gray-600">
                Showing {filteredNews.length} {filteredNews.length === 1 ? 'article' : 'articles'}
              </p>
            </div>
            
            {filteredNews.length > 0 ? (
              <>
                {/* News grid */}
                <div id="news-grid" className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {currentNews.map(newsItem => (
                    <NewsCard 
                      key={newsItem.id} 
                      news={newsItem} 
                      onLikeToggle={handleLikeToggle} 
                    />
                  ))}
                </div>
                
                {/* Pagination */}
                {totalPages > 1 && (
                  <div className="flex justify-center mt-10">
                    <nav className="flex items-center space-x-1">
                      <button
                        onClick={() => paginate(currentPage - 1)}
                        disabled={currentPage === 1}
                        className={`px-3 py-1 rounded-md ${
                          currentPage === 1 
                            ? 'text-gray-400 cursor-not-allowed' 
                            : 'text-gray-700 hover:bg-gray-200'
                        }`}
                      >
                        Previous
                      </button>
                      
                      {[...Array(totalPages)].map((_, i) => (
                        <button
                          key={i}
                          onClick={() => paginate(i + 1)}
                          className={`px-3 py-1 rounded-md ${
                            currentPage === i + 1 
                              ? 'bg-primary text-white' 
                              : 'text-gray-700 hover:bg-gray-200'
                          }`}
                        >
                          {i + 1}
                        </button>
                      ))}
                      
                      <button
                        onClick={() => paginate(currentPage + 1)}
                        disabled={currentPage === totalPages}
                        className={`px-3 py-1 rounded-md ${
                          currentPage === totalPages 
                            ? 'text-gray-400 cursor-not-allowed' 
                            : 'text-gray-700 hover:bg-gray-200'
                        }`}
                      >
                        Next
                      </button>
                    </nav>
                  </div>
                )}
              </>
            ) : (
              <div className="text-center py-10">
                <h3 className="text-xl font-semibold mb-2">No news found</h3>
                <p className="text-gray-600 mb-6">
                  Try adjusting your filters or search query to find what you're looking for.
                </p>
                <button
                  onClick={resetFilters}
                  className="bg-primary hover:bg-primary-hover text-white py-2 px-6 rounded-md transition-colors"
                >
                  Reset Filters
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default News;
