// src/components/ProductCard.tsx

import { Link } from "react-router-dom";
import { useCart } from "@/context/CartContext";
import { ShoppingCart } from "lucide-react";
import { useState } from "react";

interface ProductCardProps {
  product: {
    id: string;
    name: string;
    price: number;
    image: string;
    description: string;
    category: string;
    stock: number;
  };
}

const ProductCard = ({ product }: ProductCardProps) => {
  const { addToCart } = useCart();
  const [isHovered, setIsHovered] = useState(false);
  const [isAdding, setIsAdding] = useState(false);

  const handleAddToCart = () => {
    setIsAdding(true);
    addToCart({
      id: product.id,
      name: product.name,
      price: product.price,
      image: product.image,
    });
    
    // Reset the animation after a delay
    setTimeout(() => {
      setIsAdding(false);
    }, 500);
  };

  return (
    <div 
      className="bg-white rounded-lg shadow-md overflow-hidden transition-all duration-300 hover:-translate-y-1 hover:shadow-lg"
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
    >
      <Link to={`/products/${product.id}`} className="block relative">
        <img 
          src={product.image} 
          alt={product.name} 
          className={`w-full h-64 object-cover transition-transform duration-500 ${isHovered ? 'scale-105' : ''}`}
        />
        
        {/* Stock indicator */}
        {product.stock <= 5 && (
          <div className="absolute top-2 left-2 bg-red-500 text-white text-xs px-2 py-1 rounded">
            {product.stock === 0 ? 'Out of stock' : `Only ${product.stock} left!`}
          </div>
        )}
        
        {/* Category badge */}
        <div className="absolute top-2 right-2 bg-black bg-opacity-70 text-white text-xs px-2 py-1 rounded">
          {product.category}
        </div>
      </Link>
      
      <div className="p-4">
        <Link to={`/products/${product.id}`}>
          <h3 className="text-lg font-semibold mb-2 hover:text-primary transition-colors">{product.name}</h3>
        </Link>
        <p className="text-gray-600 text-sm mb-2 line-clamp-2">{product.description}</p>
        
        <div className="flex justify-between items-center mt-4">
          <span className="font-bold text-lg">${product.price.toFixed(2)}</span>
          
          <button 
            onClick={handleAddToCart} 
            disabled={product.stock === 0}
            className={`px-3 py-2 rounded-full flex items-center justify-center transition-all ${
              product.stock === 0 
                ? 'bg-gray-300 cursor-not-allowed' 
                : 'bg-primary hover:bg-primary-hover text-white'
            } ${isAdding ? 'scale-90' : ''}`}
          >
            <ShoppingCart className="w-5 h-5" />
          </button>
        </div>
      </div>
    </div>
  );
};

export default ProductCard;

// src/components/ProductCard.vue

<template>
  <div class="card product-card h-100">
    <router-link :to="`/products/${product.id}`" class="position-relative">
      <img :src="product.image" :alt="product.name" class="card-img-top" style="height: 200px; object-fit: cover;">
      
      <!-- Stock indicator -->
      <div v-if="product.stock <= 5" class="position-absolute top-0 start-0 m-2 badge bg-danger">
        {{ product.stock === 0 ? 'Out of stock' : `Only ${product.stock} left!` }}
      </div>
      
      <!-- Category badge -->
      <div class="position-absolute top-0 end-0 m-2 badge bg-dark">
        {{ product.category }}
      </div>
    </router-link>
    
    <div class="card-body">
      <router-link :to="`/products/${product.id}`" class="text-decoration-none">
        <h5 class="card-title">{{ product.name }}</h5>
      </router-link>
      <p class="card-text text-truncate">{{ product.description }}</p>
      
      <div class="d-flex justify-content-between align-items-center mt-2">
        <span class="fw-bold">${{ formatPrice(product.price) }}</span>
        
        <button 
          @click="addToCart" 
          :disabled="product.stock === 0"
          class="btn" 
          :class="[product.stock === 0 ? 'btn-secondary' : 'btn-primary']"
        >
          <i class="bi bi-cart-plus"></i>
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { defineProps, defineEmits } from 'vue';

const props = defineProps({
  product: {
    type: Object,
    required: true
  }
});

const emit = defineEmits(['add-to-cart']);

const formatPrice = (price) => {
  return price.toFixed(2);
};

const addToCart = () => {
  if (props.product.stock > 0) {
    emit('add-to-cart', props.product);
  }
};
</script>

<style scoped>
.product-card {
  transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.product-card:hover {
  transform: translateY(-5px);
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
}
</style>
